### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by timsayshey** [justinschw/docker-squid-e2guardian-pi#1]
Cool project. As someone totally new to all of this. 

Can you provide a quick setup guide? 

I'm wanting to set this up as a Transparent Proxy.

**Comment by justinschw** [comment]
I am sure I have done this before. You can basically provide any squid.conf
that you want. You can set up a transparent proxy there. Here is one
example of a squid transparent proxy.
https://gist.github.com/bogdanr/2aac18e64d794df6f390

From there, just map the corresponding ports and apply an iptables rule to
redirect to those ports, exactly as you would if you were doing a normal
squid install.
